title: NTokenizers
description: Documentation for the NTokenizers library
markdown: kramdown

# Sidebar configuration
sidebar:
  nav:
    - title: "Home"
      url: "/ntokenizers"
    - title: "C#"
      url: "csharp"
    - title: "Json"
      url: "json"
    - title: "Markdown"
      url: "markdown"
    - title: "Sql"
      url: "sql"
    - title: "Typescript"
      url: "typescript"
    - title: "Css"
      url: "css"
    - title: "Xml"
      url: "xml"
    - title: "Html"
      url: "html"
    - title: "Yaml"
      url: "yaml"
    - title: "Toml"
      url: "toml"
    - title: "C"
      url: "c"
    - title: "Cpp"
      url: "cpp"
    - title: "Go"
      url: "go"
    - title: "Java"
      url: "java"
    - title: "Kotlin"
      url: "kotlin"
    - title: "Rust"
      url: "rust"
    - title: "Swift"
      url: "swift"
    - title: "Encoding"
      url: "encoding"

# Breadcrumb
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"